import {
  days as tuskaDays,
  genres as tuskaGenres,
  schedule as tuskaSchedule,
  stages as tuskaStages,
} from "./schedule.js";

const nummiDays = [
  { id: "wed", short: "WED", label: "Wednesday", date: "17.6." },
  { id: "thu", short: "THU", label: "Thursday", date: "18.6." },
  { id: "fri", short: "FRI", label: "Friday", date: "19.6." },
  { id: "sat", short: "SAT", label: "Saturday", date: "20.6." },
];

const nummiStages = ["Main Stage", "Inferno Stage", "Kaaos Klubi"];

const nummiGenres = {
  "NUMMIROCK ENSEMBLE": ["Heavy Metal"],
  "SUOTANA": ["Melodic Death Metal", "Black Metal"],
  "RIASA": ["Death Metal"],
  "RUOSKA": ["Industrial Metal"],
  "VERMILIA": ["Black Metal", "Folk Metal"],
  "BARATHRUM": ["Black Metal", "Doom Metal"],
  "... AND OCEANS": ["Black Metal", "Symphonic Metal"],
  "THYRARGO": ["Death Metal"],
  "DEATHBYROMY": ["Alternative Metal", "Gothic Rock"],
  "GRAVE": ["Death Metal"],
  "SLOW FALL": ["Melodic Death Metal", "Doom Metal"],
  "ASAGRAUM": ["Black Metal"],
  "VAHINKOLAPSI": ["Punk Rock"],
  "SWALLOW THE SUN": ["Doom Metal", "Melodic Death Metal"],
  "KNEEL BEFORE THE DEATH": ["Deathcore", "Industrial Metal"],
  "GAEREA": ["Black Metal"],
  "IKINÄ": ["Alternative Metal"],
  "SATYRICON": ["Black Metal"],
  "WOLFHEART": ["Melodic Death Metal"],
  "THE GREAT SOUTHERN OSTROBOTHNIAN TRENDKILLERS": ["Groove Metal"],
  "ROCKJOOGA": ["Program"],
  "KRABELIBINGO": ["Program"],
  "STONED STATUES": ["Alternative Rock"],
  "OMNIUM GATHERUM": ["Melodic Death Metal"],
  "INBORN TENDENCY": ["Metalcore"],
  "IMMORTAL DISFIGUREMENT": ["Deathcore"],
  "PLAGUEBREEDER": ["Death Metal"],
  "MOONSORROW": ["Folk Metal", "Black Metal"],
  "EARTHERIA": ["Metalcore"],
  "DECESSUS": ["Melodic Death Metal"],
  "NOIDUIN": ["Folk Metal"],
  "STAM1NA": ["Progressive Metal", "Thrash Metal"],
  "HANGING GARDEN": ["Doom Metal", "Melodic Death Metal"],
  "KAUNIS KUOLEMATON": ["Doom Metal", "Melodic Death Metal"],
  "SEPULCHRAL CURSE": ["Death Metal"],
  "BLACK VEIL BRIDES": ["Alternative Metal", "Hard Rock"],
  "PIKAKASSA": ["Punk Rock"],
  "EMODISKO": ["Program"],
  "KALEVAUVA": ["Folk Rock"],
  "BOYCOTT": ["Hard Rock"],
  "ELÄKELÄISET": ["Folk Rock"],
  "SAA KILJUA": ["Punk Rock"],
  "NYRKKITAPPELU": ["Punk Rock"],
  "TIMO RAUTIAINEN": ["Heavy Metal"],
  "BURLESQUE": ["Program"],
  "RISE OF THE NORTHSTAR": ["Hardcore", "Metalcore"],
  "PSYCHO BATS": ["Hard Rock"],
  "GLORYHAMMER": ["Power Metal"],
  "PAARA": ["Black Metal"],
  "LOST SOCIETY": ["Metalcore", "Nu Metal", "Groove Metal"],
  "AWAKE AGAIN": ["Alternative Metal", "Metalcore"],
  "BATTLE BEAST": ["Power Metal", "Heavy Metal"],
  "STEREO TERROR": ["Program"],
};

const nummiShows = (day, stage, entries) =>
  entries.map(([artist, start]) => ({
    festival: "nummirock",
    day,
    stage,
    artist,
    start,
    genres: nummiGenres[artist] || ["Metal"],
    id: `nummirock-${day}-${start.replace(":", "")}-${artist.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  }));

const nummiSchedule = [
  ...nummiShows("wed", nummiStages[0], []),
  ...nummiShows("wed", nummiStages[1], [
    ["SUOTANA", "21:30"],
    ["RUOSKA", "23:30"],
    ["BARATHRUM", "01:30"],
  ]),
  ...nummiShows("wed", nummiStages[2], [
    ["NUMMIROCK ENSEMBLE", "20:30"],
    ["RIASA", "22:30"],
    ["VERMILIA", "00:30"],
  ]),
  ...nummiShows("thu", nummiStages[0], [
    ["... AND OCEANS", "14:30"],
    ["GRAVE", "17:30"],
    ["SWALLOW THE SUN", "20:30"],
    ["SATYRICON", "23:45"],
  ]),
  ...nummiShows("thu", nummiStages[1], [
    ["DEATHBYROMY", "16:30"],
    ["ASAGRAUM", "19:00"],
    ["GAEREA", "22:15"],
    ["WOLFHEART", "01:00"],
  ]),
  ...nummiShows("thu", nummiStages[2], [
    ["THYRARGO", "15:30"],
    ["SLOW FALL", "18:30"],
    ["VAHINKOLAPSI", "19:45"],
    ["KNEEL BEFORE THE DEATH", "21:30"],
    ["IKINÄ", "23:00"],
    ["THE GREAT SOUTHERN OSTROBOTHNIAN TRENDKILLERS", "02:00"],
  ]),
  ...nummiShows("fri", nummiStages[0], [
    ["OMNIUM GATHERUM", "14:30"],
    ["MOONSORROW", "17:30"],
    ["STAM1NA", "20:30"],
    ["BLACK VEIL BRIDES", "00:00"],
  ]),
  ...nummiShows("fri", nummiStages[1], [
    ["STONED STATUES", "13:30"],
    ["IMMORTAL DISFIGUREMENT", "16:00"],
    ["DECESSUS", "19:15"],
    ["KAUNIS KUOLEMATON", "22:30"],
    ["PIKAKASSA", "01:15"],
  ]),
  ...nummiShows("fri", nummiStages[2], [
    ["ROCKJOOGA", "12:00"],
    ["KRABELIBINGO", "12:45"],
    ["INBORN TENDENCY", "15:30"],
    ["PLAGUEBREEDER", "17:00"],
    ["EARTHERIA", "18:45"],
    ["NOIDUIN", "20:00"],
    ["HANGING GARDEN", "21:45"],
    ["SEPULCHRAL CURSE", "23:15"],
    ["EMODISKO", "02:00"],
  ]),
  ...nummiShows("sat", nummiStages[0], [
    ["ELÄKELÄISET", "14:30"],
    ["TIMO RAUTIAINEN", "17:15"],
    ["GLORYHAMMER", "20:15"],
    ["BATTLE BEAST", "00:00"],
  ]),
  ...nummiShows("sat", nummiStages[1], [
    ["BOYCOTT", "13:30"],
    ["NYRKKITAPPELU", "16:15"],
    ["RISE OF THE NORTHSTAR", "19:00"],
    ["LOST SOCIETY", "22:00"],
  ]),
  ...nummiShows("sat", nummiStages[2], [
    ["ROCKJOOGA", "12:00"],
    ["KALEVAUVA", "12:45"],
    ["SAA KILJUA", "15:30"],
    ["BURLESQUE", "18:30"],
    ["PSYCHO BATS", "19:00"],
    ["BURLESQUE", "20:00"],
    ["PAARA", "21:30"],
    ["AWAKE AGAIN", "23:00"],
    ["STEREO TERROR", "01:15"],
  ]),
];

export const festivals = {
  tuska: {
    id: "tuska",
    name: "TUSKA",
    shortName: "TUSKA",
    location: "SUVILAHTI · HELSINKI",
    dateRange: "26—28 / 06 / 2026",
    accent: "#d9ff43",
    days: tuskaDays,
    stages: tuskaStages,
    genres: tuskaGenres,
    schedule: tuskaSchedule.map((show) => ({ ...show, festival: "tuska" })),
    source: "https://tuska.fi/en/program/runningorder/",
  },
  nummirock: {
    id: "nummirock",
    name: "NUMMIROCK",
    shortName: "NUMMI",
    location: "NUMMIJÄRVI · KAUHAJOKI",
    dateRange: "17—20 / 06 / 2026",
    accent: "#ff523d",
    days: nummiDays,
    stages: nummiStages,
    genres: [...new Set(nummiSchedule.flatMap((show) => show.genres))].sort(),
    schedule: nummiSchedule,
    source: "https://nummirock.fi/ohjelma",
  },
};
