export const days = [
  { id: "fri", short: "FRI", label: "Friday", date: "26.6." },
  { id: "sat", short: "SAT", label: "Saturday", date: "27.6." },
  { id: "sun", short: "SUN", label: "Sunday", date: "28.6." },
];

export const stages = [
  "Karhu Main Stage",
  "Radio City Stage",
  "Nordic Energy Stage",
  "KVLT Stage",
];

const genreByArtist = {
  "GATECREEPER": ["Death Metal"],
  "LOST SOCIETY": ["Metalcore", "Nu Metal", "Groove Metal"],
  "PAIN": ["Industrial Metal"],
  "D-A-D": ["Hard Rock"],
  "MEGADETH": ["Thrash Metal"],
  "HOKKA": ["Alternative Metal", "Metalcore"],
  "THE PLOT IN YOU": ["Metalcore", "Alternative Metal"],
  "P.O.D.": ["Nu Metal", "Alternative Metal"],
  "TRIVIUM": ["Metalcore", "Thrash Metal"],
  "BAD OMENS": ["Metalcore", "Alternative Metal"],
  "STAM1NA": ["Progressive Metal", "Thrash Metal"],
  "TAROT": ["Heavy Metal"],
  "AMORPHIS": ["Melodic Death Metal", "Progressive Metal"],
  "BRING ME THE HORIZON": ["Metalcore", "Alternative Metal"],
  "AWAKE AGAIN": ["Alternative Metal", "Metalcore"],
  "LOUDNESS": ["Heavy Metal", "Hard Rock"],
  "BLOODRED HOURGLASS": ["Melodic Death Metal", "Metalcore"],
  "BLOOD INCANTATION": ["Death Metal", "Progressive Metal"],
  "MELROSE AVENUE": ["Metalcore", "Alternative Metal"],
  "SWALLOW THE SUN": ["Doom Metal", "Melodic Death Metal"],
  "DOGMA": ["Heavy Metal", "Hard Rock"],
  "RIVERS OF NIHIL": ["Progressive Metal", "Death Metal"],
  "CASKETS": ["Metalcore", "Post-Hardcore"],
  "ALLT": ["Metalcore", "Progressive Metal"],
  "SARA": ["Alternative Metal", "Progressive Metal"],
  "RETURN TO DUST": ["Alternative Metal", "Grunge"],
  "MALEVOLENCE": ["Metalcore", "Hardcore"],
  "AURORAWAVE": ["Metalcore", "Alternative Metal"],
  "ENSIFERUM": ["Folk Metal", "Melodic Death Metal"],
  "SKINDRED": ["Nu Metal", "Alternative Metal"],
  "WARMEN": ["Power Metal", "Melodic Death Metal"],
  "BALANCE BREACH": ["Metalcore", "Djent"],
  "MAJESTICA": ["Power Metal"],
  "THE FUNERAL PORTRAIT": ["Post-Hardcore", "Alternative Metal"],
  "PALEFACE SWISS": ["Deathcore", "Hardcore"],
  "KUBLAI KHAN TX": ["Metalcore", "Hardcore"],
  "NECKBREAKKER": ["Death Metal"],
  "SOILWORK": ["Melodic Death Metal", "Metalcore"],
  "QUEENSRŸCHE": ["Progressive Metal", "Heavy Metal"],
  "THE BROWNING": ["Metalcore", "Industrial Metal"],
  "JELLY DIXX": ["Hard Rock"],
  "ASHES OF PERISHING": ["Melodic Death Metal"],
  "SCYTHE OF SORROW": ["Melodic Death Metal"],
  "KNEEL BEFORE THE DEATH": ["Deathcore", "Industrial Metal"],
  "SLOPE": ["Hardcore", "Nu Metal"],
  "LUNARSEA": ["Melodic Death Metal"],
  "NENERCHY": ["Death Metal"],
  "DESPISER": ["Deathcore", "Hardcore"],
  "SHERE KHAN": ["Metalcore"],
  "DYING REVERIE": ["Melodic Death Metal"],
  "KALLOMÄKI": ["Folk Metal"],
  "SURVIVORS ZERO": ["Death Metal"],
  "802": ["Alternative Metal", "Nu Metal"],
  "OMNIVORTEX": ["Death Metal", "Progressive Metal"],
  "SUICIDE CHAIN": ["Hardcore", "Metalcore"],
  "NITRIK": ["Alternative Metal", "Industrial Metal"],
  "RUKOUS": ["Hardcore", "Metalcore"],
  "KAJOS": ["Black Metal", "Post-Metal"],
  "ATLAS": ["Metalcore", "Djent"],
  "NECROTIC OOZE": ["Death Metal"],
};

const shows = (day, stage, entries) =>
  entries.map(([artist, start, end]) => ({ day, stage, artist, start, end }));

export const schedule = [
  ...shows("fri", stages[0], [
    ["GATECREEPER", "14:30", "15:25"],
    ["LOST SOCIETY", "16:15", "17:15"],
    ["PAIN", "18:15", "19:15"],
    ["D-A-D", "20:15", "21:25"],
    ["MEGADETH", "22:25", "23:55"],
  ]),
  ...shows("sat", stages[0], [
    ["HOKKA", "14:15", "15:15"],
    ["THE PLOT IN YOU", "16:15", "17:10"],
    ["P.O.D.", "18:15", "19:15"],
    ["TRIVIUM", "20:15", "21:25"],
    ["BAD OMENS", "22:25", "23:55"],
  ]),
  ...shows("sun", stages[0], [
    ["STAM1NA", "15:00", "16:00"],
    ["TAROT", "17:00", "18:00"],
    ["AMORPHIS", "19:00", "20:10"],
    ["BRING ME THE HORIZON", "21:20", "22:50"],
  ]),
  ...shows("fri", stages[1], [
    ["AWAKE AGAIN", "15:30", "16:10"],
    ["LOUDNESS", "17:15", "18:15"],
    ["BLOODRED HOURGLASS", "19:15", "20:15"],
    ["BLOOD INCANTATION", "21:25", "22:25"],
  ]),
  ...shows("sat", stages[1], [
    ["MELROSE AVENUE", "13:30", "14:15"],
    ["SWALLOW THE SUN", "15:15", "16:15"],
    ["DOGMA", "17:15", "18:10"],
    ["RIVERS OF NIHIL", "19:15", "20:15"],
    ["CASKETS", "21:25", "22:25"],
  ]),
  ...shows("sun", stages[1], [
    ["ALLT", "14:30", "15:00"],
    ["SARA", "16:00", "16:55"],
    ["RETURN TO DUST", "18:00", "19:00"],
    ["MALEVOLENCE", "20:15", "21:15"],
  ]),
  ...shows("fri", stages[2], [
    ["AURORAWAVE", "15:30", "16:10"],
    ["ENSIFERUM", "17:15", "18:15"],
    ["SKINDRED", "19:15", "20:15"],
    ["WARMEN", "21:25", "22:25"],
  ]),
  ...shows("sat", stages[2], [
    ["BALANCE BREACH", "13:30", "14:15"],
    ["MAJESTICA", "15:15", "16:15"],
    ["THE FUNERAL PORTRAIT", "17:15", "18:10"],
    ["PALEFACE SWISS", "19:15", "20:15"],
    ["KUBLAI KHAN TX", "21:25", "22:25"],
  ]),
  ...shows("sun", stages[2], [
    ["NECKBREAKKER", "14:30", "15:00"],
    ["SOILWORK", "16:00", "16:55"],
    ["QUEENSRŸCHE", "18:00", "19:00"],
    ["THE BROWNING", "20:15", "21:15"],
  ]),
  ...shows("fri", stages[3], [
    ["JELLY DIXX", "14:30", "15:00"],
    ["ASHES OF PERISHING", "15:40", "16:10"],
    ["SCYTHE OF SORROW", "16:50", "17:20"],
    ["KNEEL BEFORE THE DEATH", "18:00", "18:45"],
    ["SLOPE", "19:30", "20:15"],
    ["LUNARSEA", "21:00", "21:45"],
    ["NENERCHY", "22:30", "23:20"],
  ]),
  ...shows("sat", stages[3], [
    ["DESPISER", "14:30", "15:00"],
    ["SHERE KHAN", "15:40", "16:10"],
    ["DYING REVERIE", "16:50", "17:20"],
    ["KALLOMÄKI", "18:00", "18:45"],
    ["SURVIVORS ZERO", "19:30", "20:15"],
    ["802", "21:00", "21:45"],
    ["OMNIVORTEX", "22:30", "23:10"],
  ]),
  ...shows("sun", stages[3], [
    ["SUICIDE CHAIN", "15:30", "16:00"],
    ["NITRIK", "16:40", "17:10"],
    ["RUKOUS", "17:50", "18:20"],
    ["KAJOS", "19:00", "19:45"],
    ["ATLAS", "20:30", "21:15"],
    ["NECROTIC OOZE", "22:00", "22:45"],
  ]),
].map((show) => ({
  ...show,
  id: `${show.day}-${show.artist.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  genres: genreByArtist[show.artist] || ["Metal"],
}));

export const genres = [...new Set(schedule.flatMap((show) => show.genres))].sort();
